/**
 * Creates the generations/<game-name>/ folder tree EXACTLY per generations/info.md
 * (research/, references/, reports/, assets/{sprites,background,images,sfx,music,scenes,fonts,text},
 * systems/{rules,animations,entities,ai,calls,physics,controller}, ui/{components,methods},
 * saves/, config/, render/, tests/, public/runtime/, main.ts skeleton). Distinct from
 * vite-creator, which wraps this tree in a Vite project.
 *
 * RUNTIME-GENERATED ASSET CONVENTION (info.md "Runtime-generated assets"): assets/** is for
 * BUILD-TIME assets only — game code imports them via the `@` alias and Vite fingerprints them
 * into dist/, so anything added after a build is invisible without a rebuild. Assets created at
 * PLAY time (intra-AI generation) instead go to (a) `public/runtime/` when written before deploy
 * (Vite copies public/ verbatim, URL-stable at /runtime/<file>), or (b) RxDB as data-URL docs via
 * engine/storage/runtime-assets.ts when generated in the running browser game.
 */
import { mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';

const SCAFFOLD_LOG_PREFIX = '[engine/compiler/game-scaffold]';

/**
 * The authoritative directory tree for a generated game, transcribed from generations/info.md.
 * Each entry is a POSIX-style relative path (forward slashes) from the game root. Order is
 * top-down so parents precede children. Leaf order matches info.md.
 */
export const GAME_TREE: readonly string[] = [
  'multiplayer',
  'research',
  'references',
  'reports',
  'assets',
  'assets/sprites',
  'assets/background',
  'assets/images',
  'assets/sfx',
  'assets/music',
  'assets/scenes',
  'assets/fonts',
  'assets/text',
  'systems',
  'systems/rules',
  'systems/animations',
  'systems/entities',
  'systems/ai',
  'systems/calls',
  'systems/physics',
  'systems/controller',
  'ui',
  'ui/components',
  'ui/methods',
  'saves',
  'config',
  'render',
  'tests',
  // Runtime-generated asset convention: served verbatim by Vite at /runtime/* (never imported,
  // never fingerprinted) so post-build asset drops stay URL-stable without a rebuild.
  'public',
  'public/runtime',
] as const;

/** Files (relative to game root) that the scaffold seeds with skeleton content. */
export const GAME_FILES = {
  main: 'main.ts',
  tests: 'tests/tests.ts',
} as const;

/** Result of a scaffold run — absolute paths of everything created (or already present). */
export interface ScaffoldResult {
  /** Absolute path of the game root (generations/<game-name>/). */
  gameRoot: string;
  /** Slugified game name actually used for the folder. */
  gameName: string;
  /** Absolute paths of every directory in the tree. */
  directories: string[];
  /** Absolute paths of every seeded file. */
  files: string[];
}

export interface ScaffoldOptions {
  /**
   * Parent directory under which the game folder is created. Defaults to <cwd>/generations.
   * Provided explicitly by tests (temp dir) and by the director.
   */
  generationsDir?: string;
  /** If false, throws when the game root already exists. Defaults to true (idempotent). */
  allowExisting?: boolean;
}

/**
 * Slugify a raw game title into a filesystem-safe folder name. Lowercase, non-alphanumerics
 * collapsed to single hyphens, trimmed. Falls back to "game" if nothing usable remains.
 */
export function slugifyGameName(rawName: string): string {
  if (typeof rawName !== 'string') {
    console.warn(`${SCAFFOLD_LOG_PREFIX} slugifyGameName received non-string, using fallback`);
    return 'game';
  }
  const slug = rawName
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug.length > 0 ? slug : 'game';
}

/** Default generations directory: <cwd>/generations. */
export function defaultGenerationsDir(): string {
  return path.resolve(process.cwd(), 'generations');
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch (err) {
    if (
      err &&
      typeof err === 'object' &&
      'code' in err &&
      (err as NodeJS.ErrnoException).code === 'ENOENT'
    ) {
      return false;
    }
    throw err;
  }
}

function mainSkeleton(gameName: string): string {
  return `/**
 * Entry point for generated game "${gameName}".
 * Boots the engine runtime layers and starts the main loop.
 * Generated by ${SCAFFOLD_LOG_PREFIX}; the coder agent fills the body.
 */
export async function main(): Promise<void> {
  console.log('[${gameName}] booting');
  // Runtime wiring (renderer, ecs world, storage, input, audio) is generated by the coder agent.
}

void main();
`;
}

function testsSkeleton(gameName: string): string {
  return `/**
 * Self-authored tests for generated game "${gameName}".
 * Authored + run by the tester agent (engine/testing/test-runner.ts via tsx).
 */
import assert from 'node:assert';

assert.ok(true, 'placeholder — tester agent authors real assertions');
console.log('[${gameName}] tests placeholder passed');
`;
}

/**
 * Create the full info.md directory tree for a game under generationsDir, plus the main.ts and
 * tests/tests.ts skeletons. Idempotent by default (recursive mkdir; skips files that already
 * exist so re-runs across pipeline phases never clobber generated content).
 */
export async function scaffoldGame(
  rawGameName: string,
  options: ScaffoldOptions = {},
): Promise<ScaffoldResult> {
  const gameName = slugifyGameName(rawGameName);
  const generationsDir = options.generationsDir ?? defaultGenerationsDir();
  const allowExisting = options.allowExisting ?? true;

  if (typeof generationsDir !== 'string' || generationsDir.length === 0) {
    const msg = `${SCAFFOLD_LOG_PREFIX} invalid generationsDir`;
    console.error(msg);
    throw new Error(msg);
  }

  const gameRoot = path.join(generationsDir, gameName);
  console.log(
    `${SCAFFOLD_LOG_PREFIX} scaffold start name="${rawGameName}" slug="${gameName}" root="${gameRoot}"`,
  );

  const alreadyExists = await pathExists(gameRoot);
  if (alreadyExists && !allowExisting) {
    const msg = `${SCAFFOLD_LOG_PREFIX} game root already exists and allowExisting=false: ${gameRoot}`;
    console.error(msg);
    throw new Error(msg);
  }

  const directories: string[] = [];
  const files: string[] = [];

  try {
    await mkdir(gameRoot, { recursive: true });
    directories.push(gameRoot);

    for (const rel of GAME_TREE) {
      const abs = path.join(gameRoot, rel);
      await mkdir(abs, { recursive: true });
      directories.push(abs);
    }

    // Seed skeleton files only if absent (never clobber generated content on re-runs).
    const mainAbs = path.join(gameRoot, GAME_FILES.main);
    if (!(await pathExists(mainAbs))) {
      await writeFile(mainAbs, mainSkeleton(gameName), 'utf8');
    }
    files.push(mainAbs);

    const testsAbs = path.join(gameRoot, GAME_FILES.tests);
    if (!(await pathExists(testsAbs))) {
      await writeFile(testsAbs, testsSkeleton(gameName), 'utf8');
    }
    files.push(testsAbs);

    console.log(
      `${SCAFFOLD_LOG_PREFIX} scaffold success root="${gameRoot}" dirs=${directories.length} files=${files.length}`,
    );
    return { gameRoot, gameName, directories, files };
  } catch (err) {
    console.error(`${SCAFFOLD_LOG_PREFIX} scaffold failed root="${gameRoot}":`, err);
    throw err;
  }
}

/**
 * Verify that an existing game root contains every directory and seeded file the spec requires.
 * Returns the list of missing relative paths (empty = fully scaffolded). Plain code, no agent.
 */
export async function verifyScaffold(gameRoot: string): Promise<string[]> {
  if (typeof gameRoot !== 'string' || gameRoot.length === 0) {
    const msg = `${SCAFFOLD_LOG_PREFIX} verifyScaffold received invalid gameRoot`;
    console.error(msg);
    throw new Error(msg);
  }

  const missing: string[] = [];
  const expected: string[] = [...GAME_TREE, GAME_FILES.main, GAME_FILES.tests];

  for (const rel of expected) {
    const abs = path.join(gameRoot, rel);
    if (!(await pathExists(abs))) {
      missing.push(rel);
    }
  }

  if (missing.length > 0) {
    console.warn(
      `${SCAFFOLD_LOG_PREFIX} verifyScaffold root="${gameRoot}" missing=${missing.length}`,
      missing,
    );
  } else {
    console.log(`${SCAFFOLD_LOG_PREFIX} verifyScaffold root="${gameRoot}" complete`);
  }
  return missing;
}
