/**
 * Wrap a generated game's tree (per generations/info.md) in a Vite 8 project.
 *
 * Writes the project-level files Vite needs to build the generated game that
 * game-scaffold.ts has already laid out under generations/<game>/:
 *   - vite.config.ts   (Vite 8 / Rolldown bundler; build → dist/)
 *   - index.html       (module-graph entry referencing main.ts)
 *   - package.json     (game's own deps + dev/build/preview scripts)
 *   - tsconfig.json    (strict, bundler resolution, mirrors `@` alias)
 *   - vercel.json      (SPA rewrite so client routing resolves to index.html)
 *
 * Vite 8 facts encoded here come from research/vite.md (verified 2026-06-06):
 *   - Vite 8 production builds use the Rolldown bundler; Node 20.19+/22.12+ required.
 *   - index.html lives at project ROOT and is the entry; <script type="module" src="...">.
 *   - Only VITE_-prefixed env vars reach client code.
 *   - build output → dist/; SPA on Vercel rewrites to /index.html.
 *   - resolve.alias "@" must be mirrored in tsconfig "paths".
 *
 * This module is deliberately decoupled from game-scaffold.ts (built in parallel):
 * it only consumes a small, locally-declared options shape and the on-disk tree.
 */
import { access, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';

const VITE_LOG_PREFIX = '[engine/compiler/vite-creator]';

/**
 * Inputs needed to wrap a generated game. `gameDir` must already contain the
 * info.md tree (assets/, systems/, ui/, saves/, config/, render/, tests/, main.ts).
 * game-scaffold.ts owns the tree creation; this module only adds project files.
 */
export const ViteCreatorOptionsSchema = z
  .object({
    /** Absolute path to the generated game directory (generations/<game-name>). */
    gameDir: z.string().min(1),
    /** Game slug (used as the package name + Vercel project name); npm-safe. */
    name: z.string().min(1),
    /** Human-readable title for the HTML <title>. Defaults to `name`. */
    title: z.string().min(1).optional(),
    /** Entry module relative to gameDir (the info.md tree root). Default: main.ts */
    entry: z.string().min(1).optional(),
    /** Engine runtime dependency versions to pin into the game's package.json. */
    dependencies: z.record(z.string(), z.string()).optional(),
    /** Overwrite existing project files if present. Default: true. */
    overwrite: z.boolean().optional(),
  })
  .strict();

export type ViteCreatorOptions = z.input<typeof ViteCreatorOptionsSchema>;

export interface ViteCreatorResult {
  /** Absolute path to the wrapped game directory. */
  gameDir: string;
  /** Absolute paths of every file this call wrote. */
  written: string[];
  /** Absolute paths of files skipped because they existed and overwrite=false. */
  skipped: string[];
}

/**
 * Default runtime dependencies the generated game imports (renderer/storage/ecs).
 * Versions mirror the engine's own package.json so generated games build against
 * the same libraries the runtime layers (engine/{renderer,storage,ecs,...}) expect.
 */
const DEFAULT_GAME_DEPENDENCIES: Readonly<Record<string, string>> = Object.freeze({
  bitecs: '^0.4.0',
  'pixi.js': '^8.0.0',
  rxdb: '^17.3.0',
  rxjs: '^7.8.2',
  zod: '^4.4.3',
});

const DEFAULT_DEV_DEPENDENCIES: Readonly<Record<string, string>> = Object.freeze({
  vite: '^8.0.0',
  typescript: '^6.0.3',
});

async function fileExists(target: string): Promise<boolean> {
  try {
    await access(/* turbopackIgnore: true */ target);
    return true;
  } catch {
    return false;
  }
}

function buildViteConfig(): string {
  // Vite 8 (Rolldown). No framework plugin: generated games are vanilla-TS Pixi apps.
  // `@` alias mirrored in tsconfig paths below. SPA build → dist/.
  return `import { defineConfig } from 'vite';
import path from 'node:path';

// Generated by engine/compiler/vite-creator. Vite 8 / Rolldown bundler.
export default defineConfig({
  // Runtime-generated asset convention: public/ is copied verbatim into dist/ (no import, no
  // fingerprint), so assets dropped into public/runtime/ after a build stay reachable at the
  // stable URL /runtime/<file>. Build-time assets live in assets/** and are imported via '@'.
  publicDir: 'public',
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
  build: {
    target: 'baseline-widely-available',
    outDir: 'dist',
    sourcemap: true,
  },
});
`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildIndexHtml(title: string, entry: string): string {
  // entry is referenced as an absolute module path from project root per Vite docs.
  const entryRef = entry.startsWith('/') ? entry : `/${entry}`;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="${entryRef}"></script>
  </body>
</html>
`;
}

function buildPackageJson(name: string, dependencies: Record<string, string>): string {
  const pkg = {
    name,
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies,
    devDependencies: { ...DEFAULT_DEV_DEPENDENCIES },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function buildTsConfig(): string {
  // Mirrors the engine conventions: strict, bundler resolution, `@` path alias.
  const tsconfig = {
    compilerOptions: {
      target: 'esnext',
      module: 'esnext',
      moduleResolution: 'bundler',
      lib: ['dom', 'dom.iterable', 'esnext'],
      types: ['vite/client'],
      strict: true,
      noUncheckedIndexedAccess: true,
      exactOptionalPropertyTypes: true,
      verbatimModuleSyntax: true,
      isolatedModules: true,
      moduleDetection: 'force',
      noEmit: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      paths: {
        '@/*': ['./*'],
      },
    },
    include: ['**/*.ts'],
    exclude: ['node_modules', 'dist'],
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

function buildVercelJson(): string {
  // SPA rewrite so client-side routing resolves to the built index.html.
  const cfg = {
    rewrites: [{ source: '/(.*)', destination: '/index.html' }],
  };
  return `${JSON.stringify(cfg, null, 2)}\n`;
}

/**
 * Wrap an already-scaffolded generated game in a Vite 8 project by writing the
 * project-level files (vite.config.ts, index.html, package.json, tsconfig.json,
 * vercel.json). Idempotent unless overwrite is disabled.
 *
 * @throws if options fail validation or gameDir does not exist.
 */
export async function createViteProject(options: ViteCreatorOptions): Promise<ViteCreatorResult> {
  const parsed = ViteCreatorOptionsSchema.safeParse(options);
  if (!parsed.success) {
    console.error(`${VITE_LOG_PREFIX} invalid options issues=${JSON.stringify(parsed.error.issues)}`);
    throw new Error(`${VITE_LOG_PREFIX} createViteProject: invalid options: ${parsed.error.message}`);
  }
  const { gameDir, name } = parsed.data;
  const title = parsed.data.title ?? name;
  const entry = parsed.data.entry ?? 'main.ts';
  const overwrite = parsed.data.overwrite ?? true;
  const dependencies = { ...DEFAULT_GAME_DEPENDENCIES, ...(parsed.data.dependencies ?? {}) };

  const absGameDir = path.resolve(/* turbopackIgnore: true */ gameDir);
  console.log(
    `${VITE_LOG_PREFIX} createViteProject start name=${name} gameDir=${absGameDir} entry=${entry} overwrite=${overwrite}`,
  );

  // gameDir must already exist (game-scaffold.ts produced it). Be defensive.
  if (!(await fileExists(absGameDir))) {
    console.error(`${VITE_LOG_PREFIX} gameDir does not exist gameDir=${absGameDir}`);
    throw new Error(`${VITE_LOG_PREFIX} createViteProject: gameDir does not exist: ${absGameDir}`);
  }
  // Ensure dir exists (no-op if already present); guards against partial trees.
  await mkdir(/* turbopackIgnore: true */ absGameDir, { recursive: true });

  const files: Array<{ name: string; content: string }> = [
    { name: 'vite.config.ts', content: buildViteConfig() },
    { name: 'index.html', content: buildIndexHtml(title, entry) },
    { name: 'package.json', content: buildPackageJson(name, dependencies) },
    { name: 'tsconfig.json', content: buildTsConfig() },
    { name: 'vercel.json', content: buildVercelJson() },
  ];

  const written: string[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    const target = path.join(/* turbopackIgnore: true */ absGameDir, file.name);
    if (!overwrite && (await fileExists(target))) {
      console.log(`${VITE_LOG_PREFIX} skip existing file=${file.name}`);
      skipped.push(target);
      continue;
    }
    await writeFile(/* turbopackIgnore: true */ target, file.content, 'utf8');
    console.log(`${VITE_LOG_PREFIX} wrote file=${file.name} bytes=${Buffer.byteLength(file.content, 'utf8')}`);
    written.push(target);
  }

  console.log(`${VITE_LOG_PREFIX} createViteProject done written=${written.length} skipped=${skipped.length}`);
  return { gameDir: absGameDir, written, skipped };
}
